# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 39e304c835563b71de4bb2d2fe3011bd84909db94e11b4d05176a5f06092cc181913f90633013c6e8da3ac216429ee00b4265a7ebdf75b6f97f6aa0c084b37fd

test:
  secret_key_base: c890bb84e008f6592eefa1ca29c6086b9954b3c40b6c680853f7a9bc6f4597f66c75d4d3f1acdf6e1e8871b2b322e6130a94b7efba0c4624b12c630400dcdae8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
